[package]
name = "spn"
version = "0.1.0"

[deps]
sp = "1.4.0"
argparse = ">=1.0.0"
tcc = ">=1.0.0"
toml = "1.2.0"

[[profile]]
name = "debug"
cc = "musl-gcc"
libc = "musl"
linkage = "static"


[[bin]]
name = "spn"
source = ["source/spn.c"]
include = ["include"]

[options]
foo = "bar"
baz = 69

[config.sp]
use_foo = true
