[package]
name = "spn"
version = "0.1.0"

[deps]
sp = "1.4.0"
argparse = ">=1.0.0"
utest = "1.0.0"
tcc = ">=1.0.0"
toml = "1.2.0"

[[profile]]
name = "debug"
cc = "musl-gcc"

[[profile]]
name = "macos"
cc = "clang"

[[bin]]
name = "spn"
source = ["source/spn.c"]
include = ["include"]

[[bin]]
name = "spn-test-graph"
source = ["test/graph/main.c"]
include = ["include", "source", "test/graph", "test/tools"]
