[package]
name = "spn"
version = "0.1.0"

# [deps]
# sp = "1.4.0"
# tcc = ">=1.0.0"
# toml = "1.2.0"
# utest = "1.0.0"

[deps.package]
sp = "1.6.6"
tcc = ">=1.0.0"
toml = "1.2.0"

[deps.test]
utest = "1.0.0"

[[profile]]
name = "debug"
cc = "clang"

[[profile]]
name = "macos"
cc = "clang"

[[bin]]
name = "spn"
source = ["source/spn.c"]
include = ["include"]


[[test]]
name = "graph"
source = ["test/graph/main.c"]
include = ["include", "source", "test/tools"]

[[test]]
name = "cli"
source = ["test/cli/main.c"]
include = ["include", "source", "test/tools"]
