[package]
name = "spn"

[options]
foo = "bar"
baz = 69

[[bin]]
name = "spn"
source = ["source/spn.c"]
include = ["include"]


[deps]
sp = "^1.4.0"
argparse = ">=1.0.0"
tcc = ">=1.0.0"
toml = ">=1.0.0"

[config.sp]
use_foo = true
