[package]
name = "spn"

[deps]
tcc = ">=1.0.0"
sp = ">=1.1.0"
argparse = ">=1.0.0"
toml = ">=1.0.0"

[[bin]]
name = "spn"
entry = "source/spn.c"

[[bin]]
name = "spn-test"
entry = "test/main.c"

[options]
foo = "bar"
baz = 69

[config.sp]
use_foo = true
