[package]
name = "sqlite"
repo = "sqlite/sqlite"
version = "3.51.1"
commit = "a1de06a4c639a5d741b2b424e5dfea45eaa30e70"
author = "sqlite"
maintainer = "tspader"
system_deps = ["m"]

[lib]
kinds = ["static", "shared"]
name = 'sqlite3'
